# Generated by Django 3.0.4 on 2020-04-04 16:11

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import traveldiaryapp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewedTravelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('viewer_username', models.CharField(max_length=255)),
                ('viewer_email', models.CharField(max_length=255)),
                ('viewed_username', models.CharField(max_length=255)),
                ('viewed_email', models.CharField(max_length=255)),
                ('viewed_travel_id', models.CharField(max_length=255)),
                ('viewed_travel_name', models.CharField(max_length=255)),
                ('viewed_date', models.DateTimeField(default=datetime.datetime(2020, 4, 4, 16, 11, 16, 533824))),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('note', models.TextField()),
                ('date_added', models.DateTimeField(default=datetime.datetime(2020, 4, 4, 16, 11, 16, 530841))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'db_table': 'Travel',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Userprofile',
            },
        ),
        migrations.CreateModel(
            name='TravelImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('is_main', models.BooleanField(default=False)),
                ('image', models.ImageField(max_length=255, upload_to=traveldiaryapp.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg', 'jpg', 'bmp', 'png'])])),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='traveldiaryapp.Travel')),
            ],
            options={
                'db_table': 'TravelImage',
                'unique_together': {('is_main', 'id')},
            },
        ),
    ]
